### ISSUE TITLE
Update & allow PHP 8.1

### ISSUE THREAD

**Issue by MarcHagen** [tonix-tuft/reactphp-mysql-decorator#2]
Hi,

Currently your lib forces PHP 7.x
`friends-of-reactphp/mysql` has been updated to allow PHP 8.1 , could you update your lib ?

**Comment by tonix-tuft** [comment]
Hi @MarcHagen,

thank you this issue. Support for PHP 8 has been added now starting at version `v1.7.0`.

You can upgrade `reactphp-mysql-decorator` with Composer, I have just published version `1.7.0` to Packagist.

Stay tuned!

**Comment by MarcHagen** [comment]
Thank you!

**Comment by tonix-tuft** [comment]
@MarcHagen Don't forget to star this repo if you found it useful! 😉
